version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/my-node-app
permissions:
  - object: /home/ubuntu/my-node-app
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
